project:
  type: website
  output-dir: docs

website:
  title: "Quant UX researcher's blog"
  site-url: https://wowone.github.io
  description: "Vladimir Kukushkin's personal space"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/wowone
      - icon: linkedin
        href: https://www.linkedin.com/in/vladimir-kukushkin/
      - icon: rss
        href: index.xml
  draft-mode: unlinked
format:
  html:
    theme: litera
    css: styles.css
