project:
  type: website
  output-dir: docs

website:
  title: "Vladimir Kukushkin"
  site-url: https://wowone.github.io
  description: "Vladimir Kukushkin's personal space"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/wowone
      - icon: linkedin
        href: https://www.linkedin.com/in/vladimir-kukushkin-95b6487/
      - icon: rss
        href: index.xml
format:
  html:
    theme: litera
    css: styles.css
    



